# Generated by Django 5.2.4 on 2025-12-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelayState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_load_active', models.BooleanField(default=False, help_text='Home Load Relay')),
                ('grid_sell_active', models.BooleanField(default=False, help_text='Grid Sell Relay')),
            ],
        ),
        migrations.CreateModel(
            name='SystemReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_power_watts', models.FloatField(default=0.0)),
                ('battery_discharge_watts', models.FloatField(default=0.0)),
                ('grid_power_watts', models.FloatField(default=0.0)),
                ('battery_percentage', models.FloatField(default=0.0)),
                ('relay_home_status', models.BooleanField(default=False)),
                ('relay_grid_status', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
