# Generated by Django 5.2.4 on 2025-12-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_relaystate_grid_sell_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaystate',
            name='grid_import_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemreading',
            name='relay_import_status',
            field=models.BooleanField(default=False),
        ),
    ]
